# Generated by Django 6.1.1 on 2026-10-04 00:33

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todos_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator('^[\\w-]+\\Z', 'Use letters, digits, _ and - only, without spaces.')])),
                ('colour', models.CharField(choices=[('neutral', 'Neutral'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('teal', 'Teal'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink')], default='neutral', max_length=20)),
                ('is_favourite', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'label',
                'verbose_name_plural': 'labels',
                'ordering': ('order', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0)),
                ('content', models.CharField(help_text='Inline Markdown.', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Markdown.', max_length=16000)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Priority 1'), (2, 'Priority 2'), (3, 'Priority 3'), (4, 'No priority')], default=4)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('due_string', models.CharField(blank=True, help_text='As typed.', max_length=200)),
                ('due_rule', models.TextField(blank=True, help_text='DTSTART and RRULE, if it repeats.')),
                ('due_from_completion', models.BooleanField(default=False, help_text='`every!`: the next date counts from completion.')),
                ('completion_of', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='todos_tasks.task')),
                ('labels', models.ManyToManyField(blank=True, related_name='tasks', to='todos_tasks.label')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todos_tasks.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todos_projects.project')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todos_projects.section')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ('order', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FavouriteFilter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('slug', models.SlugField(max_length=60)),
                ('order', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_favourite_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'favourite filter',
                'verbose_name_plural': 'favourite filters',
                'ordering': ('order', 'created_at'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('owner', 'slug'), name='todos_favourite_filter_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner'), name='todos_label_name_unique', violation_error_message='You already have a label with this name.'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'section', 'parent', 'order'], name='todos_tasks_project_8be4e9_idx'),
        ),
    ]
