# Generated by Django 6.1.1 on 2026-10-03 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('object_id', models.UUIDField()),
                ('start_at', models.DateTimeField(help_text='The first time it fires.')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('rule', models.TextField(blank=True, help_text='An RRULE, for one that repeats.')),
                ('next_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('done', 'Done'), ('failed', 'Failed')], default='scheduled', editable=False, max_length=20)),
                ('fired_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_error', models.TextField(blank=True, editable=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reminder',
                'verbose_name_plural': 'reminders',
                'ordering': ('next_at', 'start_at'),
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='reminders_r_content_c15a39_idx')],
            },
        ),
    ]
