/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Exchange email and password for a JWT pair. */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Blacklist a refresh token so it can no longer be rotated. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The authenticated account. */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Rotate a refresh token for a fresh pair.
         *
         *     Subclassed purely so the schema describes the real request and response;
         *     the behaviour is SimpleJWT's.
         */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create an inactive account and its profile, and email a verification link. */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
        post: operations["auth_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Activate an account from its emailed link and sign it in. */
        post: operations["auth_verify_email_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email/resend/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Send a fresh link to an unverified account.
         *
         *     Answers the same whether or not the address has an account, so it cannot be
         *     used to discover who is registered.
         */
        post: operations["auth_verify_email_resend_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Other members, as they are publicly visible. */
        get: operations["members_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Other members, as they are publicly visible. */
        get: operations["members_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Published pages. Anyone may read public ones; private ones need a session. */
        get: operations["pages_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pages/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Published pages. Anyone may read public ones; private ones need a session. */
        get: operations["pages_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Read or update the caller's profile. */
        get: operations["profiles_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Read or update the caller's profile. */
        patch: operations["profiles_me_partial_update"];
        trace?: never;
    };
    "/api/v1/site/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description What this deployment is called, so the frontend never hard-codes it. */
        get: operations["site_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/storage/uploads/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Send the file as the raw body, with the Content-Type the ticket names and a Content-Length. Only the ticket's owner may upload, once, before it expires. */
        put: operations["storage_upload"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Documents the login response body, which ``LoginSerializer`` cannot describe.
         *
         *     ``LoginSerializer`` only declares the write-only credentials it accepts, so
         *     without this the generated schema claims login returns nothing usable.
         */
        AuthResponse: {
            readonly access: string;
            readonly refresh: string;
            readonly user: components["schemas"]["User"];
        };
        /**
         * @description * `image/jpeg` - image/jpeg
         *     * `image/png` - image/png
         *     * `image/gif` - image/gif
         *     * `image/webp` - image/webp
         *     * `image/avif` - image/avif
         *     * `application/pdf` - application/pdf
         * @enum {string}
         */
        ContentTypeEnum: "image/jpeg" | "image/png" | "image/gif" | "image/webp" | "image/avif" | "application/pdf";
        Detail: {
            readonly detail: string;
        };
        /** @description Documents the single error envelope every failing response uses. */
        Error: {
            readonly error: components["schemas"]["ErrorDetail"];
        };
        /** @description The inner payload of the envelope built by ``common.exceptions``. */
        ErrorDetail: {
            readonly code: string;
            readonly message: string;
            readonly fields: {
                [key: string]: unknown;
            };
        };
        /** @description Email/password login returning a JWT pair plus the user payload. */
        Login: {
            email: string;
            password: string;
        };
        Logout: {
            refresh: string;
        };
        /** @description What a listing needs: everything but the body. */
        Page: {
            /** Format: uuid */
            readonly id: string;
            /** @description The page lives at /pages/<slug>. */
            readonly slug: string;
            readonly title: string;
            /** @description Shown in listings and link previews. */
            readonly summary: string;
            readonly visibility: components["schemas"]["Visibility6ddEnum"];
            /**
             * Format: date-time
             * @description Set when first published. A future time schedules the page.
             */
            readonly published_at: string | null;
            /** Format: date-time */
            readonly updated_at: string;
            /** @description Markdown. Raw HTML is shown as text. */
            readonly body: string;
        };
        /** @description What a listing needs: everything but the body. */
        PageSummary: {
            /** Format: uuid */
            readonly id: string;
            /** @description The page lives at /pages/<slug>. */
            readonly slug: string;
            readonly title: string;
            /** @description Shown in listings and link previews. */
            readonly summary: string;
            readonly visibility: components["schemas"]["Visibility6ddEnum"];
            /**
             * Format: date-time
             * @description Set when first published. A future time schedules the page.
             */
            readonly published_at: string | null;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PaginatedPageSummaryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PageSummary"][];
        };
        PaginatedPublicProfileList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["PublicProfile"][];
        };
        PasswordChange: {
            current_password: string;
            new_password: string;
        };
        PatchedProfile: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: email */
            readonly email?: string;
            display_name?: string;
            avatar_url?: string;
            bio?: string;
            locale?: string;
            timezone?: string;
            readonly role?: components["schemas"]["RoleEnum"];
            readonly status?: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly enrolled_at?: string;
            extra?: {
                [key: string]: string;
            };
        };
        Profile: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            display_name?: string;
            avatar_url?: string;
            bio?: string;
            locale?: string;
            timezone?: string;
            readonly role: components["schemas"]["RoleEnum"];
            readonly status: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            readonly enrolled_at: string;
            extra?: {
                [key: string]: string;
            };
        };
        /** @description What other members may see. */
        PublicProfile: {
            /** Format: uuid */
            readonly id: string;
            readonly display_name: string;
            /** Format: uri */
            readonly avatar_url: string;
            readonly bio: string;
            readonly role: components["schemas"]["RoleEnum"];
        };
        Register: {
            /** Format: email */
            email: string;
            password: string;
            display_name?: string;
        };
        /** @description No tokens: the account stays inactive until its email is verified. */
        RegisterResponse: {
            readonly detail: string;
            readonly user: components["schemas"]["User"];
            readonly profile: components["schemas"]["Profile"];
        };
        ResendVerification: {
            /** Format: email */
            email: string;
        };
        /**
         * @description * `member` - Member
         *     * `moderator` - Moderator
         *     * `admin` - Admin
         * @enum {string}
         */
        RoleEnum: "member" | "moderator" | "admin";
        Site: {
            readonly name: string;
        };
        /**
         * @description * `active` - Active
         *     * `pending` - Pending
         *     * `suspended` - Suspended
         * @enum {string}
         */
        StatusEnum: "active" | "pending" | "suspended";
        StoredObject: {
            /** Format: uuid */
            readonly id: string;
            readonly content_type: components["schemas"]["ContentTypeEnum"];
            readonly visibility: components["schemas"]["StoredObjectVisibilityEnum"];
            readonly size: number | null;
            readonly sha256: string;
            /** Format: date-time */
            readonly uploaded_at: string | null;
            readonly url: string | null;
        };
        /**
         * @description * `public` - Public, served and cached by anyone
         *     * `private` - Private, only through signed links
         * @enum {string}
         */
        StoredObjectVisibilityEnum: "public" | "private";
        /**
         * @description The refresh request really only accepts the refresh token.
         *
         *     SimpleJWT's own serializer also carries the outgoing ``access`` field, which
         *     leaks into the generated request schema as a required property.
         */
        TokenRefreshRequest: {
            refresh: string;
        };
        /** @description Both tokens come back, because ``ROTATE_REFRESH_TOKENS`` is enabled. */
        TokenRefreshResponse: {
            readonly access: string;
            readonly refresh: string;
        };
        TokenVerify: {
            token: string;
        };
        User: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Email address
             * Format: email
             */
            readonly email: string;
            readonly is_email_verified: boolean;
            /** Format: date-time */
            readonly date_joined: string;
            /** Format: date-time */
            readonly last_login: string | null;
        };
        VerifyEmail: {
            uid: string;
            token: string;
        };
        /**
         * @description * `public` - Public
         *     * `private` - Signed-in members only
         * @enum {string}
         */
        Visibility6ddEnum: "public" | "private";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Logout"];
                "application/x-www-form-urlencoded": components["schemas"]["Logout"];
                "multipart/form-data": components["schemas"]["Logout"];
            };
        };
        responses: {
            /** @description Refresh token blacklisted. */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChange"];
                "multipart/form-data": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description Password updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefreshResponse"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerify"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerify"];
                "multipart/form-data": components["schemas"]["TokenVerify"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenVerify"];
                };
            };
        };
    };
    auth_verify_email_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmail"];
                "application/x-www-form-urlencoded": components["schemas"]["VerifyEmail"];
                "multipart/form-data": components["schemas"]["VerifyEmail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_verify_email_resend_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerification"];
                "application/x-www-form-urlencoded": components["schemas"]["ResendVerification"];
                "multipart/form-data": components["schemas"]["ResendVerification"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    members_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /**
                 * @description * `member` - Member
                 *     * `moderator` - Moderator
                 *     * `admin` - Admin
                 */
                role?: "admin" | "member" | "moderator";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPublicProfileList"];
                };
            };
        };
    };
    members_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this profile. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfile"];
                };
            };
        };
    };
    pages_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /**
                 * @description * `public` - Public
                 *     * `private` - Signed-in members only
                 */
                visibility?: "private" | "public";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPageSummaryList"];
                };
            };
        };
    };
    pages_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
        };
    };
    profiles_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    profiles_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfile"];
                "multipart/form-data": components["schemas"]["PatchedProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    site_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
        };
    };
    storage_upload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "*/*": string;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredObject"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            411: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
