# Generated by Django 6.1.1 on 2026-10-04 00:38

import apps.todos.projects.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=120)),
                ('colour', models.CharField(choices=[('neutral', 'Neutral'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('teal', 'Teal'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink')], default='neutral', max_length=20)),
                ('is_inbox', models.BooleanField(default=False, editable=False)),
                ('is_favourite', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('view', models.CharField(choices=[('list', 'List'), ('board', 'Board')], default='list', max_length=10)),
                ('sort', models.CharField(choices=[('manual', 'Manual'), ('priority', 'Priority'), ('name', 'Name'), ('added', 'Date added')], default='manual', max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('invite_token', models.CharField(blank=True, db_index=True, default=apps.todos.projects.models.new_invite_token, editable=False, max_length=40)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_projects', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='todos_projects.project')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ('order', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('colour', models.CharField(choices=[('neutral', 'Neutral'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('teal', 'Teal'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink')], default='neutral', max_length=20)),
                ('is_favourite', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='todos_projects.project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='todos_projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project member',
                'verbose_name_plural': 'project members',
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='todos_projects.project')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
                'ordering': ('order', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('is_inbox', True)), fields=('owner',), name='todos_one_inbox_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='todos_one_membership'),
        ),
    ]
