# Generated by Django 6.1.1 on 2026-10-04 01:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
