# Generated by Django 6.1.1 on 2026-09-26 17:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='The page lives at /pages/<slug>.', max_length=100, unique=True)),
                ('summary', models.CharField(blank=True, help_text='Shown in listings and link previews.', max_length=300)),
                ('body', models.TextField(blank=True, help_text='Markdown. Raw HTML is shown as text.')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Signed-in members only')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='Set when first published. A future time schedules the page.', null=True)),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
