# Generated by Django 6.1.1 on 2026-10-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='The page lives at /pages?slug=<slug>.', max_length=100, unique=True),
        ),
    ]
