# Generated by Django 6.1.1 on 2026-09-26 22:55

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Waiting to be sent'), ('sending', 'Being sent'), ('sent', 'Handed to the provider'), ('failed', 'Gave up after the last attempt')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Plain text; always sent.')),
                ('html_body', models.TextField(blank=True, help_text='Sent alongside the text if set.')),
                ('from_email', models.CharField(blank=True, help_text='Blank for DEFAULT_FROM_EMAIL.', max_length=255)),
            ],
            options={
                'verbose_name': 'email message',
                'verbose_name_plural': 'email messages',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
