# Generated by Django 6.1.1 on 2026-10-04 01:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected (access was revoked)')], default='connected', max_length=20)),
                ('refresh_token', models.BinaryField(help_text='Encrypted.')),
                ('calendar_id', models.CharField(blank=True, editable=False, max_length=255)),
                ('projects', models.JSONField(blank=True, null=True)),
                ('channel_id', models.CharField(blank=True, editable=False, max_length=64)),
                ('channel_token', models.CharField(blank=True, editable=False, max_length=64)),
                ('channel_resource', models.CharField(blank=True, editable=False, max_length=255)),
                ('channel_expires_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('sync_token', models.TextField(blank=True, editable=False)),
                ('last_synced_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_error', models.TextField(blank=True, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todo_google', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Calendar connection',
                'verbose_name_plural': 'Google Calendar connections',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pushes', to='todos_google.connection')),
            ],
            options={
                'verbose_name': 'pending push',
                'verbose_name_plural': 'pending pushes',
                'constraints': [models.UniqueConstraint(fields=('connection', 'task_id'), name='todos_google_one_push')],
            },
        ),
    ]
