# Generated by Django 6.1.1 on 2026-09-10 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enabled_apps', models.JSONField(blank=True, default=list)),
                ('allow_self_enrolment', models.BooleanField(default=True)),
                ('default_settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProgramDomain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='programs.program')),
            ],
            options={
                'ordering': ('-is_primary', 'host'),
            },
        ),
    ]
