# Generated by Django 6.1.1 on 2026-09-26 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredObject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('content_type', models.CharField(choices=[('image/jpeg', 'image/jpeg'), ('image/png', 'image/png'), ('image/gif', 'image/gif'), ('image/webp', 'image/webp'), ('image/avif', 'image/avif'), ('application/pdf', 'application/pdf')], max_length=100)),
                ('max_size', models.PositiveBigIntegerField(help_text='The most bytes the upload may be.')),
                ('visibility', models.CharField(choices=[('public', 'Public, served and cached by anyone'), ('private', 'Private, only through signed links')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Waiting for the upload'), ('uploading', 'Upload in progress'), ('ready', 'Uploaded')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='The upload must finish before this.')),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'stored object',
                'verbose_name_plural': 'stored objects',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'expires_at'], name='storage_sto_status_cb6b12_idx')],
            },
        ),
    ]
