# Generated by Django 6.1.1 on 2026-10-03 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_of',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='todos.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_from_completion',
            field=models.BooleanField(default=False, help_text='`every!`: the next date counts from completion.'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_rule',
            field=models.TextField(blank=True, help_text='DTSTART and RRULE, if it repeats.'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_string',
            field=models.CharField(blank=True, help_text='As typed.', max_length=200),
        ),
    ]
