# Generated by Django 6.1.1 on 2026-10-04 00:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        ('todos_projects', '0001_initial'),
        ('todos_tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('text', models.TextField(blank=True, help_text='Markdown.', max_length=15000)),
                ('edited_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('attachment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_comment', to='storage.storedobject')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_comments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todos_projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todos_tasks.task')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('created_at',),
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('task__isnull', True), ('project__isnull', True), _connector='XOR'), name='todos_comment_on_one_thing', violation_error_message='Comment on a task or a project.')],
            },
        ),
    ]
